
server:
  port: 8080

oauth2:
  client:
    clientId: ffd03794f0a032b7e1d9
    clientSecret: f7b0d1f23f72ca1524fa5c6b925d9946aa5369f7
    redirectUri: http://localhost:8080/login/oauth2/code/github
    grantType: authorization_code
  authServer:
    authorizationEndpoint: http://localhost:8082/login/oauth/authorize
    tokenEndpoint: http://localhost:8082/login/oauth/access_token
    #authorizationEndpoint: https://github.com/login/oauth/authorize
    #tokenEndpoint: https://github.com/login/oauth/access_token
  resourceServer:
    uri: http://localhost:8081
